
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.aeropuerto.gui;

import com.mycompany.aeropuerto.dto.VueloBase;
import com.mycompany.aeropuerto.dto.VueloDiario;
import static com.mycompany.aeropuerto.logica.LogicaNegocio.escribirCSVvuelosDiarios;
import static com.mycompany.aeropuerto.logica.LogicaNegocio.getAllVuelosBase;
import static com.mycompany.aeropuerto.logica.LogicaNegocio.getAllVuelosDiarios;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/**
 *
 * @author Diego
 */
public class GestionVuelosDiarios extends javax.swing.JDialog {

    public GestionVuelosDiarios(){
     initComponents();
     cargarCbxVuelosBase();
       for (int i = 0; i < 24; i++) {
            if (i < 10) {
                x = "0";
                x = x + i;
                cbxHorasSR.addItem(x);
                cbxHorasLR.addItem(x);
            } else {
                cbxHorasSR.addItem(Integer.toString(i));
                cbxHorasLR.addItem(Integer.toString(i));
            }

        }
        for (int i = 0; i < 60; i++) {
           
                if (i < 10) {
                    y = "0";
                    y = y + i;
                    cbxMinutosSR.addItem(y);
                    cbxMinutosLR.addItem(y);
                } else {
                    cbxMinutosSR.addItem(Integer.toString(i));
                    cbxMinutosLR.addItem(Integer.toString(i));
                }

            
        }
    }
    /**
     * Creates new form GestionVuelosDiarios
     */
    public GestionVuelosDiarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        for (int i = 0; i < 24; i++) {
            if (i < 10) {
                x = "0";
                x = x + i;
                cbxHorasSR.addItem(x);
                cbxHorasLR.addItem(x);
            } else {
                cbxHorasSR.addItem(Integer.toString(i));
                cbxHorasLR.addItem(Integer.toString(i));
            }

        }
        for (int i = 0; i < 60; i++) {
           
                if (i < 10) {
                    y = "0";
                    y = y + i;
                    cbxMinutosSR.addItem(y);
                    cbxMinutosLR.addItem(y);
                } else {
                    cbxMinutosSR.addItem(Integer.toString(i));
                    cbxMinutosLR.addItem(Integer.toString(i));
                }

            
        }

    }
    String horasr;
    String ms;
    String hora;
    String x = "0";
    String y = "0";

    /*
    public void RellenarCombos(JComboBox comboHoras, JComboBox comboMinutos){
    for(int i = 0; i<24;i++){
    cbxHorasSR.addItem(Integer.toString(i));
    cbxHorasLR.addItem(Integer.toString(i));
    }
    for(int i = 0; i<60;i++){
    cbxMinutosSR.addItem(Integer.toString(i));
    cbxMinutosLR.addItem(Integer.toString(i));
    
    }
    }
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public static Date getFechaByHora(int horas, int minutos) {
        Calendar cal = Calendar.getInstance();
        cal.set(1970, 1, 1, horas, minutos);
        Date fecha = cal.getTime();
        return fecha;
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFechaVueloDiario = new javax.swing.JTextField();
        txtPlazasOcupadas = new javax.swing.JTextField();
        txtPrecioVuelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnGuardarVD = new javax.swing.JButton();
        cbxHorasSR = new javax.swing.JComboBox<>();
        cbxMinutosSR = new javax.swing.JComboBox<>();
        lblHoraSR = new javax.swing.JLabel();
        cbxHorasLR = new javax.swing.JComboBox<>();
        cbxMinutosLR = new javax.swing.JComboBox<>();
        lblHoraLR = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbxCodigoVD = new javax.swing.JComboBox<>();
        btnTablaVB = new javax.swing.JButton();
        btnNuevoVuelo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código:");

        jLabel2.setText("Fecha de vuelo:");

        jLabel3.setText("Hora salida real:");

        jLabel4.setText("Hora llegada real:");

        jLabel5.setText("Número de plazas ocupadas:");

        jLabel6.setText("Precio del vuelo:");

        btnGuardarVD.setBackground(new java.awt.Color(50, 225, 50));
        btnGuardarVD.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnGuardarVD.setText("Guardar");
        btnGuardarVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarVDActionPerformed(evt);
            }
        });

        cbxHorasSR.setToolTipText("");
        cbxHorasSR.setName(""); // NOI18N
        cbxHorasSR.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxHorasSRItemStateChanged(evt);
            }
        });
        cbxHorasSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxHorasSRActionPerformed(evt);
            }
        });

        cbxMinutosSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMinutosSRActionPerformed(evt);
            }
        });

        lblHoraSR.setText("00:00");

        cbxHorasLR.setToolTipText("");
        cbxHorasLR.setName(""); // NOI18N
        cbxHorasLR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxHorasLRActionPerformed(evt);
            }
        });

        cbxMinutosLR.setToolTipText("");
        cbxMinutosLR.setName(""); // NOI18N
        cbxMinutosLR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMinutosLRActionPerformed(evt);
            }
        });

        lblHoraLR.setText("00:00");

        jLabel9.setBackground(new java.awt.Color(255, 255, 204));
        jLabel9.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ALTA VUELO DIARIO");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cbxCodigoVD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el código" }));

        btnTablaVB.setText("Ver tabla");
        btnTablaVB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaVBActionPerformed(evt);
            }
        });

        btnNuevoVuelo.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnNuevoVuelo.setText("Nuevo vuelo");
        btnNuevoVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoVueloActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jLabel10.setText("Hora seleccionada:");

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jLabel11.setText("Hora seleccionada:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGuardarVD))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFechaVueloDiario)
                                    .addComponent(txtPlazasOcupadas)
                                    .addComponent(txtPrecioVuelo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbxHorasLR, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(cbxMinutosLR, 0, 1, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbxHorasSR, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(cbxMinutosSR, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblHoraSR, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                            .addComponent(lblHoraLR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cbxCodigoVD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnTablaVB)))))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxCodigoVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTablaVB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaVueloDiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxHorasSR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMinutosSR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoraSR)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cbxHorasLR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxMinutosLR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHoraLR)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlazasOcupadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarVD)
                    .addComponent(btnNuevoVuelo))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarVDActionPerformed
        VueloDiario vueloDiario = new VueloDiario();
        try {
            SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
            DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            //String horaSR = lblHoraSR.getText();
            //String horaLR = lblHoraLR.getText();
            
            Date fechaVuelo = dateFormat.parse(txtFechaVueloDiario.getText().toString());
           // Date horaSRFormateada = formatoHora.parse(horaSR);
           // Date horaLRFormateada = formatoHora.parse(horaLR);
            
            
            
            //esto es lo nuevo 
            int horasSR1 = Integer.parseInt(cbxHorasSR.getSelectedItem().toString());
            int minutosMS1 = Integer.parseInt(cbxMinutosSR.getSelectedItem().toString());
            Date horasalida = getFechaByHora(horasSR1,minutosMS1);
            
            int horasSL1 = Integer.parseInt(cbxHorasLR.getSelectedItem().toString());
            int minutosML1 = Integer.parseInt(cbxMinutosLR.getSelectedItem().toString());
            Date horallegada = getFechaByHora(horasSL1,minutosML1);
           
           
            
            vueloDiario.setCodigoVueloBase(cbxCodigoVD.getSelectedItem().toString());
            vueloDiario.setNumPlazasOcupadas(Integer.parseInt(txtPlazasOcupadas.getText()));
            vueloDiario.setPrecioVuelo(Float.parseFloat(txtPrecioVuelo.getText()));
            vueloDiario.setFechaVuelo(fechaVuelo);
           
            
            
            Time timehoraSR = new Time(horasalida.getTime());
            Time timehoraLR = new Time(horallegada.getTime());
            
            vueloDiario.setHoraSalidaReal(timehoraSR);
            vueloDiario.setHoraLlegadaReal(timehoraLR);
            
            System.out.println(vueloDiario.toString());
            escribirCSVvuelosDiarios(vueloDiario);
        } catch (ParseException ex) {
            System.out.println(ex.getMessage());
            //Logger.getLogger(GestionVuelosDiarios.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnGuardarVDActionPerformed
public void cargarCbxVuelosBase(){
List<VueloBase> lstVuelosBase = new ArrayList<>();
lstVuelosBase = getAllVuelosBase();

for(VueloBase vb: lstVuelosBase){
    cbxCodigoVD.addItem(vb.getCodigoVuelo());
}
}
    
    
    private void cbxHorasSRItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxHorasSRItemStateChanged
        //String h = cbxHorasSR.getSelectedItem().toString();
       


    }//GEN-LAST:event_cbxHorasSRItemStateChanged

    private void cbxMinutosSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMinutosSRActionPerformed
        horasr = cbxHorasSR.getSelectedItem() != null ? cbxHorasSR.getSelectedItem().toString() : "";
        ms = cbxMinutosSR.getSelectedItem() != null ?  cbxMinutosSR.getSelectedItem().toString() : "";
        hora = horasr + ":" + ms+":00";
        lblHoraSR.setText(hora);    }//GEN-LAST:event_cbxMinutosSRActionPerformed

    private void cbxHorasLRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxHorasLRActionPerformed
         horasr = cbxHorasLR.getSelectedItem() != null ? cbxHorasLR.getSelectedItem().toString() : "";
        ms = cbxMinutosLR.getSelectedItem() != null ?  cbxMinutosLR.getSelectedItem().toString() : "";
        hora = horasr + ":" + ms+":00";
        lblHoraLR.setText(hora);
    }//GEN-LAST:event_cbxHorasLRActionPerformed

    private void cbxHorasSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxHorasSRActionPerformed
         horasr = cbxHorasSR.getSelectedItem() != null ? cbxHorasSR.getSelectedItem().toString() : "";
        ms = cbxMinutosSR.getSelectedItem() != null ?  cbxMinutosSR.getSelectedItem().toString() : "";
        hora = horasr + ":" + ms+":00";
        lblHoraSR.setText(hora);
    }//GEN-LAST:event_cbxHorasSRActionPerformed

    private void cbxMinutosLRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMinutosLRActionPerformed
        //horasr = cbxHorasSR.getSelectedItem() != null ? cbxHorasSR.getSelectedItem().toString() : "";
        ms = cbxMinutosLR.getSelectedItem() != null ?  cbxMinutosLR.getSelectedItem().toString() : "";
        hora = horasr + ":" + ms+":00";
        lblHoraLR.setText(hora);  
    }//GEN-LAST:event_cbxMinutosLRActionPerformed

    private void btnTablaVBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaVBActionPerformed
        TablaVuelosBase tbv = new TablaVuelosBase();
        tbv.setVisible(true);
    }//GEN-LAST:event_btnTablaVBActionPerformed

    private void btnNuevoVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoVueloActionPerformed
       cbxCodigoVD.setSelectedIndex(0);
       cbxHorasSR.setSelectedIndex(0);
       cbxHorasLR.setSelectedIndex(0);
       cbxMinutosSR.setSelectedIndex(0);
       cbxMinutosSR.setSelectedIndex(0);
        txtFechaVueloDiario.setText("");
       txtPlazasOcupadas.setText("");
       txtPrecioVuelo.setText("");
    }//GEN-LAST:event_btnNuevoVueloActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionVuelosDiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionVuelosDiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionVuelosDiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionVuelosDiarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionVuelosDiarios dialog = new GestionVuelosDiarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarVD;
    private javax.swing.JButton btnNuevoVuelo;
    private javax.swing.JButton btnTablaVB;
    private javax.swing.JComboBox<String> cbxCodigoVD;
    private javax.swing.JComboBox<String> cbxHorasLR;
    private javax.swing.JComboBox<String> cbxHorasSR;
    private javax.swing.JComboBox<String> cbxMinutosLR;
    private javax.swing.JComboBox<String> cbxMinutosSR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblHoraLR;
    private javax.swing.JLabel lblHoraSR;
    private javax.swing.JTextField txtFechaVueloDiario;
    private javax.swing.JTextField txtPlazasOcupadas;
    private javax.swing.JTextField txtPrecioVuelo;
    // End of variables declaration//GEN-END:variables
}
