/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.aeropuerto.gui;

import com.mycompany.aeropuerto.dto.Aeropuerto;
import com.mycompany.aeropuerto.dto.CompanyaAerea;
import static com.mycompany.aeropuerto.logica.LogicaNegocio.actualizarCSVComp;
import static com.mycompany.aeropuerto.logica.LogicaNegocio.leerAeropuertosCSV;
import static com.mycompany.aeropuerto.logica.LogicaNegocio.leerCompanyasCSV;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author diegoposti
 */
public class ModificarComp extends javax.swing.JDialog {

    /**
     * Creates new form ModificarComp
     */
    public ModificarComp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarCBXCompanyas();
        cargarcbxModificaciones();
        cbxCambios.setVisible(false);
        pnlModCompInfo.setVisible(false);
        pnlModificar.setVisible(false);
        pnlModificaciones.setVisible(false);

    }

    private void cargarcbxModificaciones() {
        cbxCambios.addItem("Prefijo");
        cbxCambios.addItem("Código");
        cbxCambios.addItem("Nombre");
        cbxCambios.addItem("Dirección sede central");
        cbxCambios.addItem("Municipio sede central");
        cbxCambios.addItem("Teléfono información al pasajero");
        cbxCambios.addItem("Teléfono información aeropuertos");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxLstComp = new javax.swing.JComboBox<>();
        pnlModCompInfo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblModCompPrefijo = new javax.swing.JLabel();
        lblModCompCodigo = new javax.swing.JLabel();
        lblModCompNombre = new javax.swing.JLabel();
        lblModCompSedeCentral = new javax.swing.JLabel();
        lblModCompMunicipio = new javax.swing.JLabel();
        lblModCompTlfPasajeros = new javax.swing.JLabel();
        lblModCompTlfAeropuertos = new javax.swing.JLabel();
        pnlModificar = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        cbxCambios = new javax.swing.JComboBox<>();
        pnlModificaciones = new javax.swing.JPanel();
        btnGuardarCambios = new javax.swing.JButton();
        txtCambios = new javax.swing.JTextField();
        lblTituloModificar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MODIFICACIÓN COMPAÑÍAS AÉREAS");

        jLabel2.setText("Selecciona la compañía:");

        cbxLstComp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Listado de compañías" }));
        cbxLstComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLstCompActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel10.setText("Prefijo:");

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel11.setText("Código:");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setText("Dirección Sede Central:");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setText("Municipio Sede Central:");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setText("Teléfono info. pasajeros:");

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setText("Teléfono info. aeropuertos:");

        lblModCompTlfPasajeros.setToolTipText("");

        javax.swing.GroupLayout pnlModCompInfoLayout = new javax.swing.GroupLayout(pnlModCompInfo);
        pnlModCompInfo.setLayout(pnlModCompInfoLayout);
        pnlModCompInfoLayout.setHorizontalGroup(
            pnlModCompInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModCompInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlModCompInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(60, 60, 60)
                .addGroup(pnlModCompInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModCompTlfPasajeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlModCompInfoLayout.createSequentialGroup()
                        .addGroup(pnlModCompInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlModCompInfoLayout.createSequentialGroup()
                                .addGroup(pnlModCompInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblModCompPrefijo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblModCompCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblModCompNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblModCompSedeCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblModCompMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblModCompTlfAeropuertos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        pnlModCompInfoLayout.setVerticalGroup(
            pnlModCompInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModCompInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlModCompInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblModCompPrefijo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlModCompInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblModCompCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlModCompInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblModCompNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlModCompInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblModCompSedeCentral))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlModCompInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblModCompMunicipio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlModCompInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblModCompTlfPasajeros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlModCompInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblModCompTlfAeropuertos))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        btnModificar.setBackground(new java.awt.Color(255, 255, 102));
        btnModificar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        cbxCambios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el campo a modificar" }));
        cbxCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlModificarLayout = new javax.swing.GroupLayout(pnlModificar);
        pnlModificar.setLayout(pnlModificarLayout);
        pnlModificarLayout.setHorizontalGroup(
            pnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxCambios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnModificar)
                .addGap(19, 19, 19))
        );
        pnlModificarLayout.setVerticalGroup(
            pnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(cbxCambios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardarCambios.setBackground(new java.awt.Color(102, 255, 102));
        btnGuardarCambios.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnGuardarCambios.setText("Guardar cambios");
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        lblTituloModificar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlModificacionesLayout = new javax.swing.GroupLayout(pnlModificaciones);
        pnlModificaciones.setLayout(pnlModificacionesLayout);
        pnlModificacionesLayout.setHorizontalGroup(
            pnlModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModificacionesLayout.createSequentialGroup()
                .addComponent(txtCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarCambios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(pnlModificacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlModificacionesLayout.setVerticalGroup(
            pnlModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModificacionesLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(lblTituloModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCambios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarCambios)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        btnSalir.setBackground(new java.awt.Color(255, 51, 0));
        btnSalir.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(cbxLstComp, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlModificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlModCompInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxLstComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(pnlModCompInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlModificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxLstCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLstCompActionPerformed
        comp = cbxLstComp.getSelectedItem().toString();
        List<CompanyaAerea> lstComp = leerCompanyasCSV();
        for (CompanyaAerea c : lstComp) {

            int x = c.getPrefijo();
            String xS = Integer.toString(x);
            if (c.getNombre().equals(comp)) {
                lblModCompPrefijo.setText(xS);
                lblModCompCodigo.setText(c.getCodigo());
                lblModCompNombre.setText(c.getNombre());
                lblModCompSedeCentral.setText(c.getDireccion());
                lblModCompMunicipio.setText(c.getMunicipio());
                lblModCompTlfPasajeros.setText(c.getNumInfoPasajero());
                lblModCompTlfAeropuertos.setText(c.getNumInfoAeropuerto());
                pnlModCompInfo.setVisible(true);
                pnlModificar.setVisible(true);
            }
        }

    }//GEN-LAST:event_cbxLstCompActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        cbxCambios.setVisible(true);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void cbxCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCambiosActionPerformed
        btnModificar.setVisible(false);
        pnlModificaciones.setVisible(true);
        String modificacion = cbxCambios.getSelectedItem().toString();
        if (modificacion.equals("Nombre")) {
            lblTituloModificar.setText("Escribe el nuevo nombre: ");
        } else if (modificacion.equals("Prefijo")) {
            lblTituloModificar.setText("Escribe el nuevo prefijo: ");
        } else if (modificacion.equals("Código")) {
            lblTituloModificar.setText("Escribe el nuevo código: ");
        } else if (modificacion.equals("Dirección sede central")) {
            lblTituloModificar.setText("Escribe la nueva dirección: ");
        } else if (modificacion.equals("Municipio sede central")) {
            lblTituloModificar.setText("Escribe el nuevo municipio: ");
        } else if (modificacion.equals("Teléfono información al pasajero")) {
            lblTituloModificar.setText("Escribe el nuevo teléfono: ");
        } else if (modificacion.equals("Teléfono información aeropuertos")) {
            lblTituloModificar.setText("Escribe el nuevo teléfono: ");
        }
    }//GEN-LAST:event_cbxCambiosActionPerformed
String comp;
String modificacion;
    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
       
        List<CompanyaAerea> lstComp = leerCompanyasCSV();
        comp = cbxLstComp.getSelectedItem().toString();

        for (CompanyaAerea c : lstComp) {
            if (c.getNombre().equals(comp)) {
                 modificacion = cbxCambios.getSelectedItem().toString();
                if (modificacion.equals("Nombre")) {
                    c.setNombre(txtCambios.getText());
                    lblModCompNombre.setText(txtCambios.getText());

                } else if (modificacion.equals("Prefijo")) {
                    c.setPrefijo(Integer.parseInt(txtCambios.getText()));
                    lblModCompPrefijo.setText(txtCambios.getText());

                } else if (modificacion.equals("Código")) {
                    c.setCodigo(txtCambios.getText());
                    lblModCompCodigo.setText(txtCambios.getText());

                } else if (modificacion.equals("Dirección sede central")) {
                    c.setDireccion(txtCambios.getText());
                    lblModCompSedeCentral.setText(txtCambios.getText());

                } else if (modificacion.equals("Municipio sede central")) {
                    c.setMunicipio(txtCambios.getText());
                    lblModCompMunicipio.setText(txtCambios.getText());

                } else if (modificacion.equals("Teléfono información al pasajero")) {
                    c.setNumInfoPasajero(txtCambios.getText());
                    lblModCompTlfPasajeros.setText(txtCambios.getText());

                } else if (modificacion.equals("Teléfono información aeropuertos")) {
                    c.setNumInfoAeropuerto(txtCambios.getText());
                    lblModCompTlfAeropuertos.setText(txtCambios.getText());

                }

            }
        }

        actualizarCSVComp(lstComp);
        txtCambios.setText("");
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       btnModificar.setVisible(true);
        cbxCambios.setVisible(false);
        pnlModificaciones.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cargarCBXCompanyas() {
        List<CompanyaAerea> lstComp = leerCompanyasCSV();

        for (CompanyaAerea c : lstComp) {
            System.out.println(c.getNombre());
            System.out.println(c.getNombre() + " " + c.getCodigo());
            cbxLstComp.addItem(c.getNombre());
        }
    }

    ;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarComp dialog = new ModificarComp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxCambios;
    private javax.swing.JComboBox<String> cbxLstComp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblModCompCodigo;
    private javax.swing.JLabel lblModCompMunicipio;
    private javax.swing.JLabel lblModCompNombre;
    private javax.swing.JLabel lblModCompPrefijo;
    private javax.swing.JLabel lblModCompSedeCentral;
    private javax.swing.JLabel lblModCompTlfAeropuertos;
    private javax.swing.JLabel lblModCompTlfPasajeros;
    private javax.swing.JLabel lblTituloModificar;
    private javax.swing.JPanel pnlModCompInfo;
    private javax.swing.JPanel pnlModificaciones;
    private javax.swing.JPanel pnlModificar;
    private javax.swing.JTextField txtCambios;
    // End of variables declaration//GEN-END:variables
}
