/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.aeropuerto.gui;

import com.mycompany.aeropuerto.dto.CompanyaAerea;
import com.mycompany.aeropuerto.dto.VueloBase;
import com.mycompany.aeropuerto.dto.VueloDiario;
import com.mycompany.aeropuerto.logica.LogicaNegocio;
import static com.mycompany.aeropuerto.logica.LogicaNegocio.actualizarCSVComp;
import static com.mycompany.aeropuerto.logica.LogicaNegocio.getAllVuelosBase;
import static com.mycompany.aeropuerto.logica.LogicaNegocio.getAllVuelosDiarios;
import static com.mycompany.aeropuerto.logica.LogicaNegocio.getVueloBaseByCodigo;
import static com.mycompany.aeropuerto.logica.LogicaNegocio.leerCompanyasCSV;
import java.awt.Color;
import static java.lang.Integer.parseInt;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.RowSorter.SortKey;
import javax.swing.SortOrder;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Diego
 */
public class Paneles extends javax.swing.JDialog {

    TableRowSorter<SalidasTableModel> FiltrosS, FiltrosD;
    TableRowSorter<LlegadasTableModel> FiltrosL, FiltrosC;

    /**
     * Creates new form Paneles
     */
    public Paneles(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarCBXCompanyas();
        cargarCBXComp();
        pnlRecaudaciones.setVisible(false);

        List<VueloDiario> lstVueloDiarioSalidas = vuelosSalidasFiltrados();
        
        Calendar c1 = Calendar.getInstance();
        Calendar c2 = new GregorianCalendar();
        String dia = Integer.toString(c1.get(Calendar.DATE));
        String mes = Integer.toString(c1.get(Calendar.MONTH));
        String annio = Integer.toString(c1.get(Calendar.YEAR));
        Date fechaActual = new Date();

        //Código panel de salidas
        tblSalidas.setModel(new SalidasTableModel(LogicaNegocio.getAllVuelosDiarios()));
        FiltrosS = new TableRowSorter<>(new SalidasTableModel(LogicaNegocio.getAllVuelosDiarios()));
        tblSalidas.setRowSorter(FiltrosS);
        List<SortKey> skSalidas = new ArrayList<>();
        skSalidas.add(new SortKey(2, SortOrder.ASCENDING));
        FiltrosS.setSortKeys(skSalidas);
        RowFilter<SalidasTableModel, Integer> rf = RowFilter.notFilter(RowFilter.regexFilter("Aeropuerto de Asturias", 1));
        FiltrosS.setRowFilter(rf);

        //Código panel de llegadas
        tblLlegadas.setModel(new LlegadasTableModel(LogicaNegocio.getAllVuelosDiarios()));
        FiltrosL = new TableRowSorter<>(new LlegadasTableModel(LogicaNegocio.getAllVuelosDiarios()));
        TableRowSorter<LlegadasTableModel> FiltrosL = new TableRowSorter<>(new LlegadasTableModel(LogicaNegocio.getAllVuelosDiarios()));
        tblLlegadas.setRowSorter(FiltrosL);
        List<SortKey> skLlegadas = new ArrayList<>();
        skLlegadas.add(new SortKey(2, SortOrder.ASCENDING));
        FiltrosL.setSortKeys(skLlegadas);
        RowFilter<LlegadasTableModel, Integer> rfL = RowFilter.notFilter(RowFilter.regexFilter("Aeropuerto de Asturias", 1));
        FiltrosL.setRowFilter(rfL);

        tblCompanyas.setModel(new LlegadasTableModel(LogicaNegocio.getAllVuelosDiarios()));
        tblDestinos.setModel(new SalidasTableModel(lstVueloDiarioSalidas));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLlegadas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDiaLL = new javax.swing.JTextField();
        btnBuscarLlegadas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtAnyoLL = new javax.swing.JTextField();
        txtMesLL = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalidas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAnyo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCompanyas = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtDia2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMes2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtAnyo2 = new javax.swing.JTextField();
        btnBuscarFechaComp = new javax.swing.JButton();
        cbxComp = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDestinos = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        txtDia3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtMes3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtAnyo3 = new javax.swing.JTextField();
        btnBuscarFechaDestino = new javax.swing.JButton();
        cbxDestinos = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        pnlRecaudaciones = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtDiaDinero = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtMesDinero = new javax.swing.JTextField();
        lblX = new javax.swing.JLabel();
        txtAnyoDinero = new javax.swing.JTextField();
        lblIngresoEsperado = new javax.swing.JLabel();
        lblIngresoObtenido = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnRecaudaciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        tblLlegadas.setBackground(new java.awt.Color(0, 0, 0));
        tblLlegadas.setForeground(new java.awt.Color(153, 255, 51));
        tblLlegadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblLlegadas);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LLEGADAS");

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("/");

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("/");

        txtDiaLL.setBackground(new java.awt.Color(0, 0, 0));
        txtDiaLL.setForeground(new java.awt.Color(255, 255, 255));

        btnBuscarLlegadas.setBackground(new java.awt.Color(0, 255, 0));
        btnBuscarLlegadas.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnBuscarLlegadas.setText("Buscar");
        btnBuscarLlegadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLlegadasActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha:");

        txtAnyoLL.setBackground(new java.awt.Color(0, 0, 0));
        txtAnyoLL.setForeground(new java.awt.Color(255, 255, 255));

        txtMesLL.setBackground(new java.awt.Color(0, 0, 0));
        txtMesLL.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDiaLL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMesLL, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAnyoLL, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarLlegadas, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtDiaLL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txtMesLL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(txtAnyoLL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarLlegadas))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(929, 929, 929))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SALIDAS");

        tblSalidas.setBackground(new java.awt.Color(0, 0, 0));
        tblSalidas.setForeground(new java.awt.Color(153, 255, 51));
        tblSalidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblSalidas);

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha:");

        txtDia.setBackground(new java.awt.Color(0, 0, 0));
        txtDia.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("/");

        txtMes.setBackground(new java.awt.Color(0, 0, 0));
        txtMes.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("/");

        txtAnyo.setBackground(new java.awt.Color(0, 0, 0));
        txtAnyo.setForeground(new java.awt.Color(255, 255, 255));

        btnBuscar.setBackground(new java.awt.Color(0, 255, 0));
        btnBuscar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAnyo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtAnyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("VUELOS POR COMPAÑÍA");

        tblCompanyas.setBackground(new java.awt.Color(0, 0, 0));
        tblCompanyas.setForeground(new java.awt.Color(153, 255, 51));
        tblCompanyas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tblCompanyas);

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fecha:");

        txtDia2.setBackground(new java.awt.Color(0, 0, 0));
        txtDia2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("/");

        txtMes2.setBackground(new java.awt.Color(0, 0, 0));
        txtMes2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("/");

        txtAnyo2.setBackground(new java.awt.Color(0, 0, 0));
        txtAnyo2.setForeground(new java.awt.Color(255, 255, 255));

        btnBuscarFechaComp.setBackground(new java.awt.Color(0, 255, 0));
        btnBuscarFechaComp.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnBuscarFechaComp.setText("Buscar");
        btnBuscarFechaComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFechaCompActionPerformed(evt);
            }
        });

        cbxComp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comp." }));
        cbxComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCompActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Seleccionar compañía:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDia2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMes2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAnyo2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarFechaComp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtDia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtMes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtAnyo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)))
                            .addComponent(btnBuscarFechaComp, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(32, 32, 32)))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("VUELOS POR DESTINO");

        tblDestinos.setBackground(new java.awt.Color(0, 0, 0));
        tblDestinos.setForeground(new java.awt.Color(153, 255, 51));
        tblDestinos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(tblDestinos);

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Fecha:");

        txtDia3.setBackground(new java.awt.Color(0, 0, 0));
        txtDia3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("/");

        txtMes3.setBackground(new java.awt.Color(0, 0, 0));
        txtMes3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("/");

        txtAnyo3.setBackground(new java.awt.Color(0, 0, 0));
        txtAnyo3.setForeground(new java.awt.Color(255, 255, 255));

        btnBuscarFechaDestino.setBackground(new java.awt.Color(0, 255, 0));
        btnBuscarFechaDestino.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnBuscarFechaDestino.setText("Buscar");
        btnBuscarFechaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFechaDestinoActionPerformed(evt);
            }
        });

        cbxDestinos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Destino" }));
        cbxDestinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDestinosActionPerformed(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Seleccionar destino:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDia3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMes3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAnyo3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxDestinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarFechaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addComponent(jScrollPane5)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(txtDia3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(txtMes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtAnyo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxDestinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)))
                            .addComponent(btnBuscarFechaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
        );

        pnlRecaudaciones.setBackground(new java.awt.Color(102, 102, 255));

        jLabel23.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Ingreso esperado:");

        jLabel24.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Ingreso obtenido:");

        jLabel25.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Fecha:");

        jLabel26.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("día");

        jLabel27.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("mes");

        lblX.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblX.setForeground(new java.awt.Color(255, 255, 255));
        lblX.setText("año");

        lblIngresoEsperado.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblIngresoEsperado.setForeground(new java.awt.Color(0, 255, 0));

        lblIngresoObtenido.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblIngresoObtenido.setForeground(new java.awt.Color(0, 255, 0));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRecaudacionesLayout = new javax.swing.GroupLayout(pnlRecaudaciones);
        pnlRecaudaciones.setLayout(pnlRecaudacionesLayout);
        pnlRecaudacionesLayout.setHorizontalGroup(
            pnlRecaudacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecaudacionesLayout.createSequentialGroup()
                .addGroup(pnlRecaudacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRecaudacionesLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel26)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel27)
                        .addGap(29, 29, 29)
                        .addComponent(lblX))
                    .addGroup(pnlRecaudacionesLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(pnlRecaudacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblIngresoObtenido, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlRecaudacionesLayout.createSequentialGroup()
                .addGroup(pnlRecaudacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlRecaudacionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIngresoEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRecaudacionesLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiaDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMesDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAnyoDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultar)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        pnlRecaudacionesLayout.setVerticalGroup(
            pnlRecaudacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecaudacionesLayout.createSequentialGroup()
                .addGroup(pnlRecaudacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRecaudacionesLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlRecaudacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(lblX)
                            .addComponent(jLabel26)))
                    .addGroup(pnlRecaudacionesLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(pnlRecaudacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiaDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMesDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnyoDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultar)
                            .addComponent(jLabel25))))
                .addGap(21, 21, 21)
                .addGroup(pnlRecaudacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(lblIngresoEsperado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRecaudacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(lblIngresoObtenido, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnRecaudaciones.setBackground(new java.awt.Color(255, 255, 51));
        btnRecaudaciones.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnRecaudaciones.setText("Recaudaciones");
        btnRecaudaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecaudacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(562, 562, 562)
                                .addComponent(btnRecaudaciones))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(325, 325, 325)
                                .addComponent(pnlRecaudaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(btnRecaudaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRecaudaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String fechaSalidaS = txtDia.getText() + "-" + txtMes.getText() + "-" + txtAnyo.getText();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MM-yyyy");
        try {
            Date fechaConvertida = formatoFecha.parse(fechaSalidaS);
            RowFilter<SalidasTableModel, Integer> rfS = RowFilter.regexFilter(fechaSalidaS, 5);
            FiltrosS.setRowFilter(rfS);
        } catch (ParseException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cbxCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCompActionPerformed
       


    }//GEN-LAST:event_cbxCompActionPerformed
public List<VueloDiario> vuelosSalidasFiltrados(){
List<VueloDiario> lstVuelos = getAllVuelosDiarios();
List<VueloDiario> lstVuelosS = new ArrayList<>();

for(VueloDiario vd: lstVuelos){
     String codigo2 = vd.getCodigoVueloBase().toString();
     String destino2 = getVueloBaseByCodigo(codigo2).getAeropuertoDestino();
     if(!destino2.equals("Aeropuerto de Asturias")){
     lstVuelosS.add(vd);
     }
}
return lstVuelosS;
}
    
    
    
    public void cargarCBXComp() {
        List<VueloBase> lstVuelosBase = new ArrayList<>();
        lstVuelosBase = getAllVuelosBase();

        for (VueloBase vb : lstVuelosBase) {
            if(!vb.getAeropuertoDestino().equals("Aeropuerto de Asturias"))
            cbxDestinos.addItem(vb.getAeropuertoDestino());
        }
    }


    private void cbxDestinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDestinosActionPerformed
        
    }//GEN-LAST:event_cbxDestinosActionPerformed

    private void btnBuscarLlegadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLlegadasActionPerformed

        tblLlegadas.setModel(new LlegadasTableModel(LogicaNegocio.getAllVuelosDiarios()));
        FiltrosL = new TableRowSorter<>(new LlegadasTableModel(LogicaNegocio.getAllVuelosDiarios()));
        TableRowSorter<LlegadasTableModel> FiltrosL = new TableRowSorter<>(new LlegadasTableModel(LogicaNegocio.getAllVuelosDiarios()));
        tblLlegadas.setRowSorter(FiltrosL);
        List<SortKey> skLlegadas = new ArrayList<>();
        skLlegadas.add(new SortKey(2, SortOrder.ASCENDING));
        FiltrosL.setSortKeys(skLlegadas);
        String fechaLlegada = txtDiaLL.getText() + "-" + txtMesLL.getText() + "-" + txtAnyoLL.getText();
        RowFilter<LlegadasTableModel, Integer> rfL = RowFilter.regexFilter(fechaLlegada, 5);
        FiltrosL.setRowFilter(rfL);

    }//GEN-LAST:event_btnBuscarLlegadasActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        List<VueloDiario> lstVuelosDiarios = getAllVuelosDiarios();
        List<VueloBase> lstVuelosBase = getAllVuelosBase();

        double obtenido = 0;
        double esperado = 0;
        int diaFiltro = Integer.parseInt(txtDiaDinero.getText());
        int mesFiltro = Integer.parseInt(txtMesDinero.getText());
        int anyoFiltro = Integer.parseInt(txtAnyoDinero.getText());
        Date fechaFiltro = new Date(anyoFiltro - 1900, mesFiltro - 1, diaFiltro);

        for (VueloDiario vd : lstVuelosDiarios) {
            double precioVuelo = vd.getPrecioVuelo();
            int plazasOcupadas = vd.getNumPlazasOcupadas();

            Date fecha = vd.getFechaVuelo();
            if (fecha.equals(fechaFiltro)) {
                obtenido = obtenido + precioVuelo * plazasOcupadas;

                for (VueloBase vb : lstVuelosBase) {
                    if (vb.getCodigoVuelo().equals(vd.getCodigoVueloBase())) {
                        int plazas = vb.getNumPlazas();
                        esperado = esperado + plazas * precioVuelo;
                    }
                }
            }
        }
        String ingresoObtenidoFinal = String.valueOf(obtenido);
        String ingresoEsperadoFinal = String.valueOf(esperado);
        lblIngresoObtenido.setText(ingresoObtenidoFinal + "€");

        lblIngresoEsperado.setText(ingresoEsperadoFinal + "€");

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnRecaudacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecaudacionesActionPerformed
        if (pnlRecaudaciones.isVisible())
            pnlRecaudaciones.setVisible(false);
        else
            pnlRecaudaciones.setVisible(true);
    }//GEN-LAST:event_btnRecaudacionesActionPerformed

    private void btnBuscarFechaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFechaDestinoActionPerformed
        String destino = cbxDestinos.getSelectedItem().toString();
        List<VueloDiario> lstVueloDiarioFiltrado = new ArrayList<>();
        List<VueloDiario> lstVuelosDiarios = getAllVuelosDiarios();
        int diaFiltro = Integer.parseInt(txtDia3.getText());
        int mesFiltro = Integer.parseInt(txtMes3.getText());
        int anyoFiltro = Integer.parseInt(txtAnyo3.getText());
        Date fechaFiltro = new Date(anyoFiltro - 1900, mesFiltro - 1, diaFiltro);

        for (VueloDiario vd : lstVuelosDiarios) {
            String codigo2 = vd.getCodigoVueloBase().toString();
                String destino2 = getVueloBaseByCodigo(codigo2).getAeropuertoDestino();
            
            //if (vd.getFechaVuelo().equals(fechaFiltro) && !destino2.equals("Aeropuerto de Asturias")) {
                lstVueloDiarioFiltrado.add(vd);
                
                

            //}
        }

        tblDestinos.setModel(new SalidasTableModel(lstVueloDiarioFiltrado));
        TableRowSorter<SalidasTableModel> FiltrosL = new TableRowSorter<>(new SalidasTableModel(LogicaNegocio.getAllVuelosDiarios()));
        FiltrosD = new TableRowSorter<>(new SalidasTableModel(lstVueloDiarioFiltrado));

        tblDestinos.setRowSorter(FiltrosD);
        List<SortKey> skLlegadas = new ArrayList<>();
        skLlegadas.add(new SortKey(2, SortOrder.ASCENDING));
        FiltrosD.setSortKeys(skLlegadas);
        RowFilter<SalidasTableModel, Integer> rfL = RowFilter.regexFilter(destino, 1);
        FiltrosD.setRowFilter(rfL);

    }//GEN-LAST:event_btnBuscarFechaDestinoActionPerformed

    private void btnBuscarFechaCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFechaCompActionPerformed
        String companya = cbxComp.getSelectedItem().toString();
        List<VueloDiario> lstVueloDiarioFiltrado = new ArrayList<>();
        List<VueloDiario> lstVuelosDiarios = getAllVuelosDiarios();
        int diaFiltro = Integer.parseInt(txtDia2.getText());
        int mesFiltro = Integer.parseInt(txtMes2.getText());
        int anyoFiltro = Integer.parseInt(txtAnyo2.getText());
        Date fechaFiltro = new Date(anyoFiltro - 1900, mesFiltro - 1, diaFiltro);

        for (VueloDiario vd : lstVuelosDiarios) {
            if (vd.getFechaVuelo().equals(fechaFiltro)) {
                lstVueloDiarioFiltrado.add(vd);

            }
        }

        tblCompanyas.setModel(new SalidasTableModel(lstVueloDiarioFiltrado));
        TableRowSorter<SalidasTableModel> FiltrosC = new TableRowSorter<>(new SalidasTableModel(LogicaNegocio.getAllVuelosDiarios()));
        FiltrosC = new TableRowSorter<>(new SalidasTableModel(lstVueloDiarioFiltrado));

        tblCompanyas.setRowSorter(FiltrosC);
        List<SortKey> skLlegadas = new ArrayList<>();
        skLlegadas.add(new SortKey(2, SortOrder.ASCENDING));
        FiltrosC.setSortKeys(skLlegadas);
        RowFilter<SalidasTableModel, Integer> rfL = RowFilter.regexFilter(companya, 4);
        FiltrosC.setRowFilter(rfL);

    }//GEN-LAST:event_btnBuscarFechaCompActionPerformed

    /**
     * @param args the command line arguments
     */
    private void cargarCBXCompanyas() {
        List<CompanyaAerea> lstComp = leerCompanyasCSV();

        for (CompanyaAerea c : lstComp) {
            System.out.println(c.getNombre());
            System.out.println(c.getNombre() + " " + c.getCodigo());
            cbxComp.addItem(c.getNombre());
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paneles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paneles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paneles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paneles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Paneles dialog = new Paneles(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarFechaComp;
    private javax.swing.JButton btnBuscarFechaDestino;
    private javax.swing.JButton btnBuscarLlegadas;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnRecaudaciones;
    private javax.swing.JComboBox<String> cbxComp;
    private javax.swing.JComboBox<String> cbxDestinos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblIngresoEsperado;
    private javax.swing.JLabel lblIngresoObtenido;
    private javax.swing.JLabel lblX;
    private javax.swing.JPanel pnlRecaudaciones;
    private javax.swing.JTable tblCompanyas;
    private javax.swing.JTable tblDestinos;
    private javax.swing.JTable tblLlegadas;
    private javax.swing.JTable tblSalidas;
    private javax.swing.JTextField txtAnyo;
    private javax.swing.JTextField txtAnyo2;
    private javax.swing.JTextField txtAnyo3;
    private javax.swing.JTextField txtAnyoDinero;
    private javax.swing.JTextField txtAnyoLL;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtDia2;
    private javax.swing.JTextField txtDia3;
    private javax.swing.JTextField txtDiaDinero;
    private javax.swing.JTextField txtDiaLL;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtMes2;
    private javax.swing.JTextField txtMes3;
    private javax.swing.JTextField txtMesDinero;
    private javax.swing.JTextField txtMesLL;
    // End of variables declaration//GEN-END:variables
}
